services:
  - type: web
    name: image-recognizer-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn image_tagging_api:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HF_TOKEN
        sync: false

